version: "3.7"

services:
  spring_boot:
    container_name: spring_boot
    image: ${SPRING_BOOT_IMAGE}
    ports:
      - "8080:8080" # 프론트 수정되면 지우기
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_URL}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PASSWORD: ${REDIS_PASSWORD}
      FRONTEND_BASE-URL: ${BASE_URL}
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    expose:
      - "6379"

  nginx:
    image: oriddle/oriddle-frontend:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - spring_boot

volumes:
  my-db:
